name: Internship Pinger

on:
  schedule:
    - cron: "*/5 * * * *"     
  workflow_dispatch:       

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore state cache
        uses: actions/cache@v4
        with:
          path: latest_internship.json
          key: internship-state-v1

      - name: Run pinger
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER:  ${{ secrets.PUSHOVER_USER }}
        run: python pinger.py

      - name: Save state artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: latest-internship-state
          path: latest_internship.json
          if-no-files-found: ignore
